development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: yak_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: yak_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  encoding: unicode
  database: yak_production
  pool:     5
